[package]
name = "RemoteRelayRust"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = { version = "1.0.108", features = [] }
rocket = "0.5.0"
lazy_static = "1.4.0"
serde = "1.0.193"
dotenv_codegen = "0.15.0"
