[package]
name = "remote_relay_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = { version = "1.0.120", features = [] }
rocket = "0.5.1"
serde = "1.0.204"
dotenv_codegen = "0.15.0"


[package.metadata.precommit]
fmt = "cargo fmt"
